spring:
  application:
    name: calendar_service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:postgresql://localhost:5434/postgres-calendar
#    url: ${DATASOURCE_URL}
    username: postgres
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: UTCv
    show-sql: true

server:
  port: 8083