version: "3.9"

services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432