spring:
  application:
    name: main_service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: n0tDrivingDrunk118
    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true