spring:
  application:
    name: main_service

  datasource:
    #url: jdbc:postgresql://localhost:5432/postgres
    url: ${DATASOURCE_URL}
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8084